`peer network login` usage message is wrong
The `peer network login` command does not specify that it
requires a username argument:

$ peer network login
Error: Must supply username
Usage:
  peer network login [flags]

This change modifies the usage message to:

Usage:
  peer network login <username> [flags]

Change-Id: I7ffbc312a9ee33ba34584c4cb57d091ffeb4b2dc
Signed-off-by: Bradley Gorman <bgorman@au1.ibm.com>